### ISSUE TITLE
Gesture outline can get out of sync with note positions

### ISSUE THREAD

**Issue by ProfJanetDavis** [WhitmanSWDesignSpring2018/project-5-8-teamjuan#10]
Maybe it's snapping to wrong line?

**Comment by ProfJanetDavis** [comment]
![Screen Shot 2019-04-12 at 12 26 39 PM](https://user-images.githubusercontent.com/19829843/56061433-459f9880-5d1e-11e9-8850-da8c36c888dc.png)

**Comment by ProfJanetDavis** [comment]
Clicking a note outside of the line does not select the gesture.

**Comment by ellehcimzhang** [comment]
Whoops.

**Comment by mjkohl32** [comment]
Don't know how to fix it
