### ISSUE TITLE
MoveableRect.updateCoordinates() is not self-explanatory

### ISSUE THREAD

**Issue by ProfJanetDavis** [WhitmanSWDesignSpring2018/project-5-8-teamjuan#19]
Needs more documentation. Why is this necessary? Why is it public? Can you think of a more self-explanatory name?

https://github.com/WhitmanSWDesignSpring2018/project-5-8-teamjuan/blob/7f7c74d4a07bba1395efa5767d4355493751488f/src/tunecomposer/MoveableRect.java#L24

**Comment by ellehcimzhang** [comment]
Changed the name to match the intention behind the method.
