### ISSUE TITLE
Rename MoveableRect.inLastFive() to be more self-explanatory

### ISSUE THREAD

**Issue by ProfJanetDavis** [WhitmanSWDesignSpring2018/project-5-8-teamjuan#20]
https://github.com/WhitmanSWDesignSpring2018/project-5-8-teamjuan/blob/7f7c74d4a07bba1395efa5767d4355493751488f/src/tunecomposer/MoveableRect.java#L71

**Comment by ellehcimzhang** [comment]
Changed names to match the intention behind inLastFive better -- right edge.
