### ISSUE TITLE
The concept "Duration" does not agree with the concept of a "MoveableRect"

### ISSUE THREAD

**Issue by ProfJanetDavis** [WhitmanSWDesignSpring2018/project-5-8-teamjuan#21]
Rename this and related methods for a more consistent interface.

https://github.com/WhitmanSWDesignSpring2018/project-5-8-teamjuan/blob/7f7c74d4a07bba1395efa5767d4355493751488f/src/tunecomposer/MoveableRect.java#L81

**Comment by ellehcimzhang** [comment]
Changed -- startWidthChange, stopWidthChange, etc.
