### ISSUE TITLE
Use dynamic method invocation instead of a conditional

### ISSUE THREAD

**Issue by ProfJanetDavis** [WhitmanSWDesignSpring2018/project-5-8-teamjuan#28]
https://github.com/WhitmanSWDesignSpring2018/project-5-8-teamjuan/blob/4730ef5b919ceb4bfe70577e2c0d6b2d09339b82/src/tunecomposer/HistoryManager.java#L21

**Comment by ellehcimzhang** [comment]
Closing this -- this issue will be eliminated through refactoring and implementing the FXML for cut/copy/paster.
